### Quiz

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [5]:
import numpy as np # NumPy 라이브러리를 가져온다.

a = np.array(['강아지', '원숭이', '꽃', 45, 100]) # np.array 함수를 사용해 정수 문자 혼합 리스트
a, a.ndim, a.size, type(a), a.dtype, a.shape


# a : 배열 a 그대로
# a.ndim : 배열의 차원의 수
# a,size : 배열의 요소 총 개수
# type(a) : a의 타입 
# a.dtype : 배열의 데이터 타입 정수형 문자형 둘 다 라서 문자형 ? 
# a.shape : 배열의 각 차워의 크기 

(array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U11'),
 1,
 5,
 numpy.ndarray,
 dtype('<U11'),
 (5,))

#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.ones((2, 3))

# np.ones : 괄호 안에 지정된 형태의 새로운 배열을 생성하고, 모든 요소를 1로 초기화함
# ((2,3)) : 함수에 전달된 인자는 배열의 형태를 정의함. 여기서는 2행 3열의 배열을 의미함

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [8]:
arr=np.arange(51,81).reshape(6,5)

#np.arange(51,81) : 51~81까지 배열
#.reshape(6,5) : 6행 5열 

arr

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [10]:
arr = arr.astype(float)
arr.dtype

# .astype(float) : float 형태로 변경

dtype('float64')

#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [19]:
import numpy as np

# 2차원 배열 생성
array2d = np.array([[ 1,  4,  5,  6],
                    [56, 23, 45, 67],
                    [ 8,  4,  6, 10]])

# 2차원 배열을 1차원 배열로 변환
array_flattened = array2d.flatten()

# 1차원 배열에서 특정 범위의 요소 슬라이싱
# 5번 인덱스부터 10번 인덱스까지 요소 선택

sliced_array = array_flattened[5:11]  

print(array_flattened)
print(sliced_array)

[ 1  4  5  6 56 23 45 67  8  4  6 10]
[23 45 67  8  4  6]


#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [20]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr[0] = 10
arr[7:] = 0
arr

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [21]:
# 2차원 5행 5열 난수
np.random.randint(0,99,25).reshape(5,5)

array([[ 6, 19, 15, 40, 93],
       [ 4, 62, 30, 72, 14],
       [31,  8, 38, 75, 12],
       [26, 72, 10, 40, 24],
       [84, 60, 90, 34, 13]])

#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [23]:
# 1~100 무작위

num = np.random.randint(1,100,7)

max_value = np.max(num)
min_value = np.min(num)

print(max_value)
print(min_value)

83
6


#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1 
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
c = np.array([[21, 22, 23], [24, 25, 26], [27, 28, 29]])

# 행 방향으로 병합

result1 = np.hstack((a, b, c))

print(result1)

# 열 방향으로 병합

result2 = np.vstack((a, b, c))

print(result2)


[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]
 [ 7  8  9 17 18 19 27 28 29]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [27]:
# arr 배열 0부터 99까지 100개의 숫자 중 40개만 무작위, replace=false 중복허용 x

arr = np.random.choice(100, 40, replace=False)

arr, arr[np.where(arr > 50)]



(array([ 9,  8, 43, 83, 39,  1, 52, 71, 35, 93, 66, 87, 76, 23, 42, 40, 89,
        65, 50, 15, 91, 79, 22, 97, 51, 57, 47, 13, 36, 32, 62, 70, 86, 31,
        99, 69, 98, 80, 34, 63]),
 array([83, 52, 71, 93, 66, 87, 76, 89, 65, 91, 79, 97, 51, 57, 62, 70, 86,
        99, 69, 98, 80, 63]))

#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [29]:
kor = np.array( [60,55,70,30,20,90])

# 1. 국어점수가 가장큰값을 구하여라

print(max(kor))


# 2. 국어점수가 80점이상인 값을 구하여라

print(kor[(kor>=80)])


# 3. 국어 점수가 50점이상 80점 이하(AND)인 값을 구하여라

print(kor[(kor>= 50) & (kor <=80)])


# 4. 국어점수의 평균을 구하여라(AVERAGE)

print(np.average(kor), round(kor.mean(),3))


# 5. 국어점수의 총합을 구하여라.

print(np.sum(kor))


# 6. 국어점수가 40점이하인 데이터를 삭제하여라

import copy
a = kor.copy()
num = kor[kor<=40]
print(a, num, np.delete(a, np.where(kor<=40)))


# 7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라

print(np.where(kor>=50, kor*1.1, kor )) 


# 8. 국어점수 top 3를 구하여라

np.sort(kor)
np.sort(kor)[::-1]
np.argsort(kor)[::-1][:3]
np.sort(kor)[::-1][:3], kor[np.argsort(kor)[::-1][:3]]


# 9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

kor, np.where(kor>=70, "합격", "불합격")



90
[90]
[60 55 70]
54.166666666666664 54.167
325
[60 55 70 30 20 90] [30 20] [60 55 70 90]
[66.  60.5 77.  30.  20.  99. ]


(array([60, 55, 70, 30, 20, 90]),
 array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3'))